INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A1', 'Autostrada Del Sole', 'Napoli', 'Milano', 803.5);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A4', 'Serenissima', 'Milano Fiorenza', 'Brescia Ovest', 93.5);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A7', 'La Serravalle', 'Serravalle Scrivia', 'Genova Ovest', 50.0);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A8', 'Autostrada Dei Laghi', 'Milano', 'Varese', 43.6);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A9', 'Autostrada Dei Laghi', 'Linate', 'Ponte Chiasso', 31.5);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A10', 'Autostrada Dei Fiori', 'Genova', 'Savona', 45.5);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A11', 'Autostrada Firenze-Mare', 'Firenze', 'Pisa Nord', 87.7);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A12', 'Autostrada Azzurra', 'Civitavecchia', 'Roma', 65.4);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A13', 'Autostrada Bologna Padova', 'Bologna', 'Padova', 127.3);
INSERT INTO Autostrada VALUES (seqAutostrada.NEXTVAL, 'A14', 'Autostrada Adriatica', 'Bologna', 'Taranto', 781.4);
/
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Napoli', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Milano', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Milano Fiorenza', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Brescia Ovest', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Serravalle Scrivia', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Genova Ovest', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Milano Est', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Varese', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Linate', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Ponte Chiasso', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Genova', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Savona', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Firenze', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Pisa Nord', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Civitavecchia', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Roma', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Bologna Ovest', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Padova', seqDirezione2.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Bologna', seqDirezione1.NEXTVAL);
INSERT INTO DirezioneTratta VALUES (seqDirezioneTratta.NEXTVAL, 'Taranto', seqDirezione2.NEXTVAL);
/
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 1);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 131.8, 1);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 431.8, 1);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 731.8, 1);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 35.8, 2);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 350.8, 2);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 679.8, 2);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 800.8, 2);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 3);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 70.8, 3);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 20.8, 4);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 60.8, 4);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 20.8, 5);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 45.8, 5);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 11.8, 6);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 41.8, 6);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 11.8, 7);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 40.8, 7);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 7.8, 8);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 37.8, 8);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 13.8, 9);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 19.8, 10);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 11);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 12.8, 11);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 41.8, 12);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 11.8, 12);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 21.8, 13);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 61.8, 13);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 14);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 71.8, 14);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 11.8, 15);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 41.8, 15);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 10.8, 16);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 45.8, 16);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 17);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 80.8, 17);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 103.8, 17);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 20.8, 18);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 60.8, 18);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 80.8, 18);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 31.8, 19);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 231.8, 19);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 431.8, 19);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 631.8, 19);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 731.8, 19);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 36.8, 20);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 153.8, 20);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 280.81, 20);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 420.8, 20);
INSERT INTO Area VALUES (seqArea.NEXTVAL, 600.8, 20);
/
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Parcheggio VALUES  (seqParcheggio.NEXTVAL, 'T', seqAreaParcheggio.NEXTVAL);
/
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'AX325FC', 'Mercedes', 'GLA', 1900, 'B', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'FRDMSG1', 'Ford', 'Mustang', 90020, '5', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'SH743RE', 'Fiat', '500', 500, 'B', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'UE566GB', 'Ford', 'Fiesta', 1400, 'B', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'GEN01LE', 'Ford', 'Focus', 5900, '4', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'CS689NN', 'Mercedes', 'T999', 12000, '4', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'UO433JK', 'Fiat', 'Iveco', 19000, '5', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'WS789TY', 'Ferrari', 'Enzo', 6000, 'B', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'DS443DL', 'Porsche', 'Carrera', 2900, '3', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'YU778KJ', 'Mercedes', 'Small', 2900, '3', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'PO332SA', 'Honda', 'T-Max', 540, 'A', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'LI679NA', 'Kawasaki', 'Z800', 800, 'A', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'NA543PO', 'Ducati', 'Monster', 1000, 'A', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'MI111LI', 'Land Rover', 'Evoque', 1999, 'B', 0);
INSERT INTO Veicolo VALUES (seqVeicolo.NEXTVAL, 'CA098KL', 'Fiat', 'Ducato', 2990, '3', 0);
/
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Napoli' , 1.5 , 1 , 1 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Milano Est' , 803 , 88 , 1 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Milano Fiorenza' , 1.5 , 12 , 2 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Brescia Ovest' , 93 ,20, 2 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Serravalle Scrivia' , 1.5 , 7 , 3 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Genova Ovest' , 49.5 , 10 , 3 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Milano' , 1.5 , 87, 4 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Varese' , 43 , 22 , 4 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Linate' , 1.5 , 17 , 5 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Ponte Chiasso' , 31 , 30 , 5 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Genova' , 1.5 , 998, 6 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Savona' , 45, 2 , 6 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Firenze' , 1.5 , 27 , 7 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Pisa Nord' , 87 , 19, 7 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Civitavecchia' , 1.5 , 3 , 8 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Roma' , 65 , 30, 8 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Bologna Nord' , 1.5 , 12 , 9 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Padova' , 127 , 11 , 9 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Bologna' , 1.5 , 12, 10 );
INSERT INTO Casello  VALUES (seqCasello.NEXTVAL , 'Taranto' , 781 , 5 , 10);
/
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,   5, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 105, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 205, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 505, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 605, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 705, 130, 'Tutor', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,   5, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 105, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 205, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 505, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 605, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 705, 130, 'Tutor', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,   5, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 105, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 205, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 505, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 605, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 705, 130, 'Tutor', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,   5, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 105, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 205, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 505, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 605, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 705, 130, 'Tutor', 20);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,  5, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 15, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 35, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 50, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 70, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 90, 130, 'Tutor', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL,  5, 130, 'Tutor', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 15, 130, 'Tutor', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 25, 130, 'Tutor', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 35, 130, 'Tutor', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Tutor', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 1);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 2);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 3);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 4);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 5);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 6);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 7);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 8);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 30, 130, 'Autovelox', 9);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 7, 130, 'Autovelox', 10);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 11);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 12);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 13);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 14);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 15);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 16);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 17);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 18);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 19);
INSERT INTO ControlloElettronico VALUES (seqControlloElettronico.NEXTVAL, 40, 130, 'Autovelox', 20);
/
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'F' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'F' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'F', 'T' , 'F', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'F', 'T' , 'T', 'T', 'T' , 'T', 'F', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'F' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'F', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'F', 'T' , 'T', 'T', 'T' , 'T', 'T', 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'F', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'F' , 'T', 'T', 'T' , 'T', 'F', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'F', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'F', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'F', 'T' , 'T', 'T', 'T' , 'T', 'T', 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'F', 'T', 'F' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'F', 'T' , 'T', 'F', 'T' , 'T', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'F', 'T', 'T' , 'F', 'T', 'T', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'T', 'T' , 'T', 'T', 'T' , 'T', 'T', 'F', seqAreaParcheggio.NEXTVAL);
INSERT INTO Servizio VALUES (seqServizio.NEXTVAL, 'F', 'T' , 'T', 'T', 'T' , 'T', 'F', 'T', seqAreaParcheggio.NEXTVAL);
/
INSERT INTO InformazioneLive VALUES (1, 6, 560, 'COLLISIONE AUTO', SYSDATE, 1);
INSERT INTO InformazioneLive VALUES (2, 8, 14, 'INCIDENTE', SYSDATE, 10);
INSERT INTO InformazioneLive VALUES (3, 15, 20, 'FOOD EVENT', SYSDATE, 12);
INSERT INTO InformazioneLive VALUES (4, 40, 50, 'RALLENTAMENTI', SYSDATE, 19);
INSERT INTO InformazioneLive VALUES (5, 86, 86, 'INCIDENTE', SYSDATE, 15);
INSERT INTO InformazioneLive VALUES (6, 1, 800, 'LAVORI IN CORSO',SYSDATE, 2);
/
INSERT INTO Incidente VALUES (1, 'INCIDENTE1', 2, 5, 2);
INSERT INTO Incidente VALUES (2, 'INCIDENTE1', 6, 7, 5);
/
INSERT INTO Rallentamento VALUES (1, 4);
/
INSERT INTO LavoroInCorso VALUES(1,6);
/
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 10, 1, 2, 3);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 100, 1, 3, 6);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 10, 2, 5, 9);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 40, 6, 7, 14);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 30, 8, 9, 17);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 200, 10, 5, 10);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 300, 10, 2, 3);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 400, 1, 2, 4);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 500, 10, 8, 16);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 50, 2, 6, 11);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 4, 6, 9, 18);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 7, 3, 10, 20);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 14, 5, 7, 13);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 1, 1);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 1, 2);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 2, 3);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 2, 4);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 3, 5);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 3, 6);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 4, 7);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 4, 8);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 5, 9);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 5, 10);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 6, 11);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 6, 12);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 7, 13);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 7, 14);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 8, 15);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 8, 16);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 9, 17);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 9, 18);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 10, 19);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 1, NULL, 10, 20);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 803.5 , 1, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 93.5 , 2, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 50 , 3, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 43.6 , 4, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 31.5 , 5, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 45.5 , 6, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 87.7 , 7, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 65.4 , 8, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 127.3 , 9, NULL, NULL);
INSERT INTO Svincolo VALUES  (seqSvincolo.NEXTVAL, 781.4 , 10, NULL, NULL);
/
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1, 130, 'Linate', SYSDATE, 2, NULL,  NULL, 23);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1, 130, 'Linate', SYSDATE, 5, NULL ,  NULL, 23);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1.5, 130, 'Linate', SYSDATE, 2, 9,  NULL, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1.5, 130, 'Linate', SYSDATE, 5, 9,  NULL, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 7, 130, 'Linate', SYSDATE, 2, NULL, 44 , NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 7, 130, 'Linate', SYSDATE, 5, NULL, 44 , NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1, 130, 'Napoli', TO_DATE ('2015-Dic-31-11-30-55', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, NULL, 15);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 1.5, 130, 'Napoli', TO_DATE ('2015-Dic-31-11-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, 1, NULL, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 5, 130, 'San Giorgio a Cremano', TO_DATE ('2015-Dic-31-12-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 7, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 105, 130, 'Formia', TO_DATE ('2015-Dic-31-13-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 8, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 205, 130, 'Gotham', TO_DATE ('2015-Dic-31-14-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 9, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 505, 130, 'Firenze', TO_DATE ('2015-Dic-31-15-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 10, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 605, 130, 'Wonderland', TO_DATE ('2015-Dic-31-16-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 11, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 705, 130, 'Bologna', TO_DATE ('2015-Dic-31-17-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, 12, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 803, 130, 'Milano', TO_DATE ('2015-Dic-31-18-30-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, 2, NULL, NULL);
INSERT INTO CheckPointTappaViaggio VALUES (seqCheckPointTappaViaggio.NEXTVAL, 803.5, 130, 'Milano', TO_DATE ('2015-Dic-31-18-31-01', 'YYYY-Mon-DD-HH24-Mi-SS'), 1, NULL, NULL, 34);
/
COMMIT;
