CREATE SEQUENCE seqArea                   INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqAreaParcheggio         INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqAutostrada             INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqCasello                INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqCheckPointTappaViaggio INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqControlloElettronico   INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqDirezione2             INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqDirezione1             INCREMENT BY 1 START WITH 1; 
CREATE SEQUENCE seqDirezioneTratta        INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqInfoLive               INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqParcheggio             INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqServizio               INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqSvincolo               INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqPercorso               INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seqVeicolo                INCREMENT BY 1 START WITH 1;
/
COMMIT;
