package it.Barbuto.Zullo;

/**
 *
 * @author Barbuto Salvatore e Zullo Stefano
 */

public class Principale extends javax.swing.JFrame {

    public Principale() {
        initComponents();
        Login l = new Login(this, true);
      l.setVisible(true);
      if (l.getPremuto() == Login.PREMUTO_ANNULLA) {
         dispose();
      } else {
         setVisible(true);
      }
    }
    
    public Principale(int ret) {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Autostrada = new javax.swing.JButton();
        DirezioneTratta = new javax.swing.JButton();
        Svincolo = new javax.swing.JButton();
        Casello = new javax.swing.JButton();
        CheckpointTappaViaggio = new javax.swing.JButton();
        Area = new javax.swing.JButton();
        Servizio = new javax.swing.JButton();
        Parcheggio = new javax.swing.JButton();
        Veicolo = new javax.swing.JButton();
        ControlloVelocita = new javax.swing.JButton();
        ControlloElettronico = new javax.swing.JButton();
        InformazioneLive = new javax.swing.JButton();
        Incidente = new javax.swing.JButton();
        Rallentamento = new javax.swing.JButton();
        LavoroInCorso = new javax.swing.JButton();
        MenuLabel = new javax.swing.JLabel();
        Pedaggio = new javax.swing.JButton();
        PercorsoVeicolo = new javax.swing.JButton();
        PercorsoCaselli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rete Autostradale - Menù");

        Autostrada.setText("Autostrade");
        Autostrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutostradaActionPerformed(evt);
            }
        });

        DirezioneTratta.setText("Direzioni Autostrade");
        DirezioneTratta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirezioneTrattaActionPerformed(evt);
            }
        });

        Svincolo.setText("Svincoli");
        Svincolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SvincoloActionPerformed(evt);
            }
        });

        Casello.setText("Caselli");
        Casello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaselloActionPerformed(evt);
            }
        });

        CheckpointTappaViaggio.setText("Checkpoint Tappa Viaggio");
        CheckpointTappaViaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckpointTappaViaggioActionPerformed(evt);
            }
        });

        Area.setText("Aree");
        Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaActionPerformed(evt);
            }
        });

        Servizio.setText("Aree di Servizio");
        Servizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServizioActionPerformed(evt);
            }
        });

        Parcheggio.setText("Piazzole");
        Parcheggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcheggioActionPerformed(evt);
            }
        });

        Veicolo.setText("Veicoli");
        Veicolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeicoloActionPerformed(evt);
            }
        });

        ControlloVelocita.setText("Controlli Velocità");
        ControlloVelocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlloVelocitaActionPerformed(evt);
            }
        });

        ControlloElettronico.setText("Controlli Elettronici");
        ControlloElettronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlloElettronicoActionPerformed(evt);
            }
        });

        InformazioneLive.setText("InformazioniLive");
        InformazioneLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformazioneLiveActionPerformed(evt);
            }
        });

        Incidente.setText("Incidenti");
        Incidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncidenteActionPerformed(evt);
            }
        });

        Rallentamento.setText("Rallentamenti");
        Rallentamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RallentamentoActionPerformed(evt);
            }
        });

        LavoroInCorso.setText("LavoriInCorso");
        LavoroInCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LavoroInCorsoActionPerformed(evt);
            }
        });

        MenuLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        MenuLabel.setText("Menù Principale");

        Pedaggio.setText("Pedaggio");
        Pedaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedaggioActionPerformed(evt);
            }
        });

        PercorsoVeicolo.setText("Percorso del Veicolo");
        PercorsoVeicolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercorsoVeicoloActionPerformed(evt);
            }
        });

        PercorsoCaselli.setText("Percorso tra Caselli");
        PercorsoCaselli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercorsoCaselliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformazioneLive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Veicolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ControlloVelocita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Rallentamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LavoroInCorso)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Incidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ControlloElettronico, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Servizio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Parcheggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(CheckpointTappaViaggio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pedaggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PercorsoVeicolo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuLabel)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PercorsoCaselli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(Autostrada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirezioneTratta, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Casello, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Svincolo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Autostrada)
                    .addComponent(Svincolo)
                    .addComponent(Casello)
                    .addComponent(DirezioneTratta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckpointTappaViaggio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ControlloElettronico)
                    .addComponent(ControlloVelocita)
                    .addComponent(Veicolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InformazioneLive)
                    .addComponent(Incidente)
                    .addComponent(LavoroInCorso)
                    .addComponent(Rallentamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Area)
                    .addComponent(Servizio)
                    .addComponent(Parcheggio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pedaggio)
                    .addComponent(PercorsoVeicolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PercorsoCaselli)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncidenteActionPerformed
        Incidente i = new Incidente();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_IncidenteActionPerformed

    private void ServizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServizioActionPerformed
        Servizio s = new Servizio();
        s.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ServizioActionPerformed

    private void AutostradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutostradaActionPerformed
        Autostrada a = new Autostrada();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AutostradaActionPerformed

    private void DirezioneTrattaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirezioneTrattaActionPerformed
        DirezioneTratta dt = new DirezioneTratta();
        dt.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_DirezioneTrattaActionPerformed

    private void ControlloElettronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlloElettronicoActionPerformed
        ControlloElettronico ce = new ControlloElettronico();
        ce.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ControlloElettronicoActionPerformed

    private void AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaActionPerformed
        Area area = new Area();
        area.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AreaActionPerformed

    private void CaselloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaselloActionPerformed
        Casello cas = new Casello();
        cas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CaselloActionPerformed

    private void RallentamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RallentamentoActionPerformed
        Rallentamento ral = new Rallentamento();
        ral.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RallentamentoActionPerformed

    private void LavoroInCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LavoroInCorsoActionPerformed
        LavoroInCorso lic = new LavoroInCorso();
        lic.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LavoroInCorsoActionPerformed

    private void InformazioneLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformazioneLiveActionPerformed
        InformazioneLive il = new InformazioneLive();
        il.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_InformazioneLiveActionPerformed

    private void ControlloVelocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlloVelocitaActionPerformed
        ControlloVelocita cv = new ControlloVelocita();
        cv.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ControlloVelocitaActionPerformed

    private void VeicoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeicoloActionPerformed
        Veicolo v = new Veicolo();
        v.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_VeicoloActionPerformed

    private void CheckpointTappaViaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckpointTappaViaggioActionPerformed
       CheckpointTappaViaggio ctv = new CheckpointTappaViaggio();
       ctv.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_CheckpointTappaViaggioActionPerformed

    private void SvincoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SvincoloActionPerformed
       Svincolo sv = new Svincolo();
       sv.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_SvincoloActionPerformed

    private void ParcheggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcheggioActionPerformed
       Parcheggio p = new Parcheggio();
       p.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_ParcheggioActionPerformed

    private void PedaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedaggioActionPerformed
        Pedaggio p = new Pedaggio();
        p.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PedaggioActionPerformed

    private void PercorsoVeicoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercorsoVeicoloActionPerformed
        PercorsoVeicolo pv = new PercorsoVeicolo();
        pv.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PercorsoVeicoloActionPerformed

    private void PercorsoCaselliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercorsoCaselliActionPerformed
       PercorsoTraCaselli ptc = new PercorsoTraCaselli();
       ptc.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_PercorsoCaselliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Area;
    private javax.swing.JButton Autostrada;
    private javax.swing.JButton Casello;
    private javax.swing.JButton CheckpointTappaViaggio;
    private javax.swing.JButton ControlloElettronico;
    private javax.swing.JButton ControlloVelocita;
    private javax.swing.JButton DirezioneTratta;
    private javax.swing.JButton Incidente;
    private javax.swing.JButton InformazioneLive;
    private javax.swing.JButton LavoroInCorso;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JButton Parcheggio;
    private javax.swing.JButton Pedaggio;
    private javax.swing.JButton PercorsoCaselli;
    private javax.swing.JButton PercorsoVeicolo;
    private javax.swing.JButton Rallentamento;
    private javax.swing.JButton Servizio;
    private javax.swing.JButton Svincolo;
    private javax.swing.JButton Veicolo;
    // End of variables declaration//GEN-END:variables
}
